ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_REACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ONBOARDING_COMPLETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROFILE_UPDATED';

ALTER TABLE "User"
  ADD COLUMN "phone" TEXT,
  ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "onboardingCompletedAt" TIMESTAMP(3);

CREATE INDEX "User_tenantId_isActive_idx" ON "User"("tenantId", "isActive");
