'use client';
import { useState } from 'react';

const tips=[{n:1,text:'Toca "Nueva solicitud" y cuéntanos qué está pasando.'},{n:2,text:'Adjunta una foto si ayuda a explicar el problema.'},{n:3,text:'Haz seguimiento del estado en cualquier momento desde Mis PQRS.'}];
function Logo(){return <svg width="34" height="34" viewBox="0 0 128 128" style={{display:'block',margin:'0 auto 20px'}} aria-hidden="true"><path d="M24 8h80c8.837 0 16 7.163 16 16v64c0 8.837-7.163 16-16 16H48l-16 16c-2.52 2.52-8 1.087-8-3V104c-8.837 0-16-7.163-16-16V24C8 15.163 15.163 8 24 8z" fill="#122545"/><path d="M40 62l17 17 31-34" fill="none" stroke="#FFFFFF" strokeWidth="11" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export default function PqrsResidentOnboardingPage(){
 const [step,setStep]=useState(0),[name,setName]=useState('Diego Salazar'),[tower,setTower]=useState('Torre 2'),[apt,setApt]=useState('402'); const next=()=>setStep(s=>Math.min(2,s+1));
 const field={width:'100%',height:44,padding:'0 14px',border:'1.5px solid #E8E8ED',borderRadius:11,fontSize:13.5,fontFamily:"'Manrope',sans-serif"} as const;
 return <><style jsx global>{`@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');*{box-sizing:border-box}body{margin:0;background:#fff}::selection{background:#EAEEF6;color:#122545}a{color:#122545;text-decoration:none}@keyframes apl-up{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}}input:focus{outline:none;border-color:#122545!important;box-shadow:0 0 0 3.5px rgba(18,37,69,.12)}`}</style>
 <main style={{minHeight:'100vh',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',background:'#FFFFFF',fontFamily:"'Manrope',sans-serif",color:'#1D1D1F',padding:24}}><div style={{width:'100%',maxWidth:420}}>
  <div style={{display:'flex',alignItems:'center',gap:6,justifyContent:'center',marginBottom:28}}>{[0,1,2].map(i=><div key={i} style={{width:i===step?20:7,height:7,borderRadius:999,background:i===step?'#122545':'#E8E8ED',transition:'width 250ms'}}/>)}</div>
  <div key={step} style={{animation:'apl-up 400ms cubic-bezier(.2,.7,.2,1) both'}}>
   {step===0&&<div style={{textAlign:'center'}}><Logo/><h1 style={{fontSize:23,fontWeight:800,letterSpacing:'-0.02em',margin:'0 0 10px'}}>Hola, Diego 👋</h1><p style={{fontSize:14,color:'#6E6E73',fontWeight:500,lineHeight:1.6,margin:'0 0 30px'}}>Bienvenido a PQRS Services, tu canal directo con la administración de Parque Residencial Calle 100.</p><div onClick={next} style={{background:'#122545',color:'#FFFFFF',textAlign:'center',fontSize:14.5,fontWeight:700,padding:'13px 0',borderRadius:999,cursor:'pointer'}}>Comenzar</div></div>}
   {step===1&&<div><div style={{fontSize:11.5,color:'#8E8E93',fontWeight:700,letterSpacing:'0.04em',marginBottom:6}}>PASO 1 DE 2</div><h1 style={{fontSize:20,fontWeight:800,letterSpacing:'-0.02em',margin:'0 0 20px'}}>Completa tu perfil</h1><label style={{display:'block',fontSize:12.5,fontWeight:700,marginBottom:7}}>Nombre completo</label><input value={name} onChange={e=>setName(e.target.value)} style={{...field,marginBottom:14}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginBottom:26}}><div><label style={{display:'block',fontSize:12.5,fontWeight:700,marginBottom:7}}>Torre</label><input value={tower} onChange={e=>setTower(e.target.value)} style={field}/></div><div><label style={{display:'block',fontSize:12.5,fontWeight:700,marginBottom:7}}>Apartamento</label><input value={apt} onChange={e=>setApt(e.target.value)} style={field}/></div></div><div onClick={next} style={{background:'#122545',color:'#FFFFFF',textAlign:'center',fontSize:14.5,fontWeight:700,padding:'13px 0',borderRadius:999,cursor:'pointer'}}>Continuar</div></div>}
   {step===2&&<div style={{textAlign:'center'}}><div style={{fontSize:11.5,color:'#8E8E93',fontWeight:700,letterSpacing:'0.04em',marginBottom:6}}>PASO 2 DE 2</div><h1 style={{fontSize:20,fontWeight:800,letterSpacing:'-0.02em',margin:'0 0 22px'}}>¿Cómo creo una solicitud?</h1><div style={{display:'flex',flexDirection:'column',gap:12,marginBottom:28,textAlign:'left'}}>{tips.map(t=><div key={t.n} style={{display:'flex',gap:12,background:'#F5F5F7',borderRadius:14,padding:'14px 16px'}}><div style={{width:26,height:26,borderRadius:999,background:'#122545',color:'#FFFFFF',display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:800,flexShrink:0}}>{t.n}</div><span style={{fontSize:13,color:'#1D1D1F',fontWeight:600,lineHeight:1.5}}>{t.text}</span></div>)}</div><a href="/residente" style={{display:'block',background:'#122545',color:'#FFFFFF',textAlign:'center',fontSize:14.5,fontWeight:700,padding:'13px 0',borderRadius:999}}>Ir a mi Centro de Estado</a></div>}
  </div>
 </div></main></>;
}
