ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REPORT_GENERATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REPORT_EXPORTED';

CREATE TYPE "Prioridad" AS ENUM ('ALTA', 'MEDIA', 'BAJA');

ALTER TABLE "Pqrs" ADD COLUMN "prioridad" "Prioridad" NOT NULL DEFAULT 'MEDIA';
