import { LegalLayout, LegalList, LegalSection } from '@/components/legal/LegalLayout';
import { getLegalConfig } from '@/lib/legal';

export default function PrivacyPage() {
  const legal = getLegalConfig();
  return <LegalLayout title="Politica de tratamiento de datos" intro="Explicamos como PQRS Services trata los datos de administradores, consejeros, residentes y contactos de los conjuntos.">
    <LegalSection title="1. Responsable y encargado"><p>El responsable legal del tratamiento debe completarse con los datos de la persona natural o juridica que opere PQRS Services. En la operacion con conjuntos residenciales, el conjunto normalmente define los fines del tratamiento de los datos de sus residentes y PQRS Services actua como encargado tecnologico siguiendo sus instrucciones.</p><p>Solicitudes de privacidad: <a href={`mailto:${legal.privacyEmail}`} style={linkStyle}>{legal.privacyEmail}</a>.</p></LegalSection>
    <LegalSection title="2. Datos que podemos tratar"><LegalList items={['Identificacion y datos de contacto de usuarios.', 'Rol, conjunto, bloque y apartamento cuando el conjunto los requiera.', 'Credenciales protegidas y datos necesarios para autenticacion.', 'Contenido de PQRS, ubicacion, evidencias, respuestas, estados e historial.', 'Notificaciones, registros de auditoria y datos tecnicos necesarios para seguridad.', 'Datos de contrato, facturacion y pagos del conjunto.']} /></LegalSection>
    <LegalSection title="3. Finalidades"><LegalList items={['Crear y administrar cuentas e invitaciones.', 'Prestar el servicio de gestion y seguimiento de PQRS.', 'Enviar notificaciones operativas y correos transaccionales.', 'Atender soporte, seguridad, auditoria y prevencion de fraude.', 'Procesar pagos, renovaciones y obligaciones contables.', 'Cumplir obligaciones legales y responder solicitudes de titulares.']} /></LegalSection>
    <LegalSection title="4. Proveedores y transferencias"><p>Para operar la plataforma utilizamos proveedores de infraestructura, almacenamiento, correo, autenticacion y pagos, como Supabase, Vercel, Resend y Mercado Pago cuando corresponda. Estos proveedores solo deben tratar la informacion necesaria para prestar sus servicios y bajo las obligaciones contractuales aplicables. Algunos pueden operar desde fuera de Colombia.</p></LegalSection>
    <LegalSection title="5. Conservacion y eliminacion"><p>Conservamos la informacion durante la vigencia de la cuenta o contrato y por el tiempo adicional necesario para cumplir obligaciones legales, resolver controversias, mantener auditoria y proteger el servicio. Al terminar el contrato, el conjunto puede solicitar la devolucion o eliminacion de la informacion conforme al acuerdo aplicable, salvo retenciones legalmente exigidas.</p></LegalSection>
    <LegalSection title="6. Derechos y solicitudes"><p>Los titulares pueden conocer, actualizar, rectificar y solicitar la supresion de sus datos, asi como consultar el uso que se les ha dado, de acuerdo con la normativa colombiana. La solicitud debe incluir nombre, correo, relacion con el conjunto y una descripcion clara del requerimiento.</p></LegalSection>
    <LegalSection title="7. Seguridad e incidentes"><p>Aplicamos controles de acceso por rol y conjunto, autenticacion, almacenamiento protegido, auditoria y copias de respaldo. Ningun servicio conectado a internet es absolutamente invulnerable. Si detectamos un incidente, activaremos el procedimiento de respuesta y las comunicaciones que correspondan.</p></LegalSection>
    <LegalSection title="8. Vigencia y cambios"><p>Esta politica entra en vigor en la fecha que se complete en la configuracion legal del sitio. Los cambios relevantes se comunicaran por los canales disponibles.</p></LegalSection>
  </LegalLayout>;
}

const linkStyle = { color: '#122545', fontWeight: 700 } as const;
